/*************************************************************
 *
 *  Copyright (c) 2026 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * @file Mappings file for the thermodynamics package.
 *
 * @author kaiserkarl31@yahoo.com (Karl D. Hammond)
 */

import ParseMethods from '../ParseMethods.js';
import ThermodynamicsMethods from './ThermodynamicsMethods.js';
import { CommandMap,EnvironmentMap } from '../TokenMap.js';

/**
 * Macros for the thermodynamics package
 */
new CommandMap ('Thermodynamics-macros', {
  AreaSymbol: [ThermodynamicsMethods.Macro, 'a'],
  TotalEnergySymbol: [ThermodynamicsMethods.Macro, 'E'],
  EnthalpySymbol: [ThermodynamicsMethods.Macro, 'H'],
  EntropySymbol: [ThermodynamicsMethods.Macro, 'S'],
  GibbsSymbol: [ThermodynamicsMethods.Macro, 'G'],
  HelmholtzSymbol: [ThermodynamicsMethods.Macro, 'A'],
  InternalEnergySymbol: [ThermodynamicsMethods.Macro, 'U'],
  compressibilitysymbol: [ThermodynamicsMethods.Macro, '\\kappa'],
  expansivitysymbol: [ThermodynamicsMethods.Macro, '\\alpha'],
  heatcapacitysymbol: [ThermodynamicsMethods.Macro, 'C'],
  dbar: [ThermodynamicsMethods.Macro, '\u0111'],
  ncomponents: [ThermodynamicsMethods.Macro, 'C'],
  extensive: [ThermodynamicsMethods.Macro,
    "{\\mkern1mu\\underline{\\mkern-1mu #1\\mkern-4mu}\\mkern4mu}", 1],
  intensive: [ThermodynamicsMethods.Macro, "#1", 1],
  specific: [ThermodynamicsMethods.Macro, "\\hat{#1}", 1],
  residual: [ThermodynamicsMethods.Macro, "{{R}}"],
  excess: [ThermodynamicsMethods.Macro, "{{E}}"],
  partialmolar: ThermodynamicsMethods.PartialMolarMacro,
  NewExtensiveProperty: ThermodynamicsMethods.NewExtensiveProperty,
  NewPartialMolarProperty: ThermodynamicsMethods.NewPartialMolarProperty,
  NewExcessProperty: ThermodynamicsMethods.NewExcessProperty,
  NewResidualProperty: ThermodynamicsMethods.NewResidualProperty,
  NewThermodynamicProperty: ThermodynamicsMethods.NewThermodynamicProperty,
  At: [ThermodynamicsMethods.Macro, '\\extensive{\\AreaSymbol}'],
  Am: [ThermodynamicsMethods.Macro, '\\intensive{\\AreaSymbol}'],
  As: [ThermodynamicsMethods.Macro, '\\specific{\\AreaSymbol}'],
  Et: [ThermodynamicsMethods.Macro, '\\extensive{\\TotalEnergySymbol}'],
  Em: [ThermodynamicsMethods.Macro, '\\intensive{\\TotalEnergySymbol}'],
  Es: [ThermodynamicsMethods.Macro, '\\specific{\\TotalEnergySymbol}'],
  Epm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\TotalEnergySymbol}'],
  Ft: [ThermodynamicsMethods.Macro, '\\extensive{\\HelmholtzSymbol}'],
  Fm: [ThermodynamicsMethods.Macro, '\\intensive{\\HelmholtzSymbol}'],
  Fs: [ThermodynamicsMethods.Macro, '\\specific{\\HelmholtzSymbol}'],
  FR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\HelmholtzSymbol}','\\residual'],
  FE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\HelmholtzSymbol}','\\excess'],
  Fpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\HelmholtzSymbol}'],
  FRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\HelmholtzSymbol}','\\residual'],
  FEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\HelmholtzSymbol}','\\excess'],
  Gt: [ThermodynamicsMethods.Macro, '\\extensive{\\GibbsSymbol}'],
  Gm: [ThermodynamicsMethods.Macro, '\\intensive{\\GibbsSymbol}'],
  Gs: [ThermodynamicsMethods.Macro, '\\specific{\\GibbsSymbol}'],
  Gpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\GibbsSymbol}'],
  GR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\GibbsSymbol}','\\residual'],
  GE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\GibbsSymbol}','\\excess'],
  GRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\GibbsSymbol}','\\residual'],
  GEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\GibbsSymbol}','\\excess'],
  Ht: [ThermodynamicsMethods.Macro, '\\extensive{\\EnthalpySymbol}'],
  Hm: [ThermodynamicsMethods.Macro, '\\intensive{\\EnthalpySymbol}'],
  Hs: [ThermodynamicsMethods.Macro, '\\specific{\\EnthalpySymbol}'],
  Hpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\EnthalpySymbol}'],
  HR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EnthalpySymbol}','\\residual'],
  HE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EnthalpySymbol}','\\excess'],
  HRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EnthalpySymbol}','\\residual'],
  HEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EnthalpySymbol}','\\excess'],
  Lt: [ThermodynamicsMethods.Macro, '\\extensive{\\Omega}'],
  Lm: [ThermodynamicsMethods.Macro, '\\intensive{\\Omega}'],
  Ls: [ThermodynamicsMethods.Macro, '\\specific{\\Omega}'],
  Nt: [ThermodynamicsMethods.Macro, 'n'],
  Qt: [ThermodynamicsMethods.Macro, '\\extensive{Q}'],
  Qm: [ThermodynamicsMethods.Macro, '\\intensive{Q}'],
  Qs: [ThermodynamicsMethods.Macro, '\\specific{Q}'],
  St: [ThermodynamicsMethods.Macro, '\\extensive{\\EntropySymbol}'],
  Sm: [ThermodynamicsMethods.Macro, '\\intensive{\\EntropySymbol}'],
  Ss: [ThermodynamicsMethods.Macro, '\\specific{\\EntropySymbol}'],
  Spm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\EntropySymbol}'],
  SR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EntropySymbol}','\\residual'],
  SE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EntropySymbol}','\\excess'],
  SRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EntropySymbol}','\\residual'],
  SEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EntropySymbol}','\\excess'],
  Ut: [ThermodynamicsMethods.Macro, '\\extensive{U}'],
  Um: [ThermodynamicsMethods.Macro, '\\intensive{U}'],
  Us: [ThermodynamicsMethods.Macro, '\\specific{U}'],
  UR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{U}','\\residual'],
  UE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{U}','\\excess'],
  Upm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\InternalEnergySymbol}'],
  URpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\InternalEnergySymbol','\\residual'],
  UEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\InternalEnergySymbol','\\excess'],
  Vt: [ThermodynamicsMethods.Macro, '\\extensive{V}'],
  Vm: [ThermodynamicsMethods.Macro, '\\intensive{V}'],
  Vs: [ThermodynamicsMethods.Macro, '\\specific{V}'],
  Vpm: [ThermodynamicsMethods.Macro, '\\partialmolar{V}'],
  VR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{V}','\\residual'],
  VE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{V}','\\excess'],
  VRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\VolumeSymbol','\\residual'],
  VEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\VolumeSymbol','\\excess'],
  Wt: [ThermodynamicsMethods.Macro, '\\extensive{W}'],
  Wm: [ThermodynamicsMethods.Macro, '\\intensive{W}'],
  Ws: [ThermodynamicsMethods.Macro, '\\specific{W}'],
  cP: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\intensive{\\heatcapacitysymbol}', 'P'],
  cPt: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\extensive{\\heatcapacitysymbol}', 'P'],
  cPs: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\specific{\\heatcapacitysymbol}', 'P'],
  cPpm: [ThermodynamicsMethods.PartialMolarSubscripted,
        '\\intensive{\\heatcapacitysymbol}', 'P'],
  cVpm: [ThermodynamicsMethods.PartialMolarSubscripted,
        '\\intensive{\\heatcapacitysymbol}', 'V'],
  cV: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\intensive{\\heatcapacitysymbol}', 'V'],
  cVt: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\extensive{\\heatcapacitysymbol}', 'V'],
  cVs: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\specifc{\\heatcapacitysymbol}', 'V'],
  kappaT: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\compressibilitysymbol', 'T'],
  kappaS: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\compressibilitysymbol', 'S'],
  alphaP: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\expansivitysymbol', 'P'],
  alphaS: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\expansivitysymbol', 'S'],
  muJT: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\mu', '\\text{JT}'],
  fpure: [ThermodynamicsMethods.Macro, 'f'],
  fmix: [ThermodynamicsMethods.Macro, '\\hat f'],
  phipure: [ThermodynamicsMethods.Macro, '\\phi'],
  phimix: [ThermodynamicsMethods.Macro, '\\hat\\phi'],
  actabs: [ThermodynamicsMethods.Macro, '\\lambda'],
  actrel: [ThermodynamicsMethods.Macro, 'a'],
  muit: [ThermodynamicsMethods.Macro, '\\mu'],
  gammait: [ThermodynamicsMethods.Macro, '\\gamma'],
  gammarat: [ThermodynamicsMethods.Macro, '\\gamma^*'],
  gammamol: [ThermodynamicsMethods.Macro, '\\gamma^\\Box'],
  Henryrat: [ThermodynamicsMethods.Macro, 'h'],
  Henrymol: [ThermodynamicsMethods.Macro, '\\mathcal{H}'],
  sat: [ThermodynamicsMethods.Macro, '\\text{sat}'],
  fsat: [ThermodynamicsMethods.Macro, 'f^{\\sat}'],
  Psat: [ThermodynamicsMethods.Macro, 'P^{\\sat}'],
  Pvap: [ThermodynamicsMethods.Macro, 'P^{\\sat}'],
  phisat: [ThermodynamicsMethods.Macro, '\\phi^{\\sat}'],
  std: [ThermodynamicsMethods.Macro, '\\circ'],
  Cstd: [ThermodynamicsMethods.Macro, 'C^{\\std}'],
  fstd: [ThermodynamicsMethods.Macro, 'f^{\\std}'],
  Pstd: [ThermodynamicsMethods.Macro, 'P^{\\std}'],
  mustd: [ThermodynamicsMethods.Macro, '\\mu^{\\std}'],
  mixing: [ThermodynamicsMethods.Macro, '\\text{mix}'],
  formation: [ThermodynamicsMethods.Macro, 'f'],
  fusion: [ThermodynamicsMethods.Macro, '\\text{fusion}'],
  reaction: [ThermodynamicsMethods.Macro, '\\text{rxn}'],
  sublimation: [ThermodynamicsMethods.Macro, '\\text{sublimation}'],
  vaporization: [ThermodynamicsMethods.Macro, '\\text{vaporization}'],
  Deltaf: [ThermodynamicsMethods.ChangeonSomething, "\\formation"],
  Deltamix: [ThermodynamicsMethods.ChangeonSomething, "\\mixing"],
  Deltarxn: [ThermodynamicsMethods.ChangeonSomething, "\\reaction"],
  Deltafus: [ThermodynamicsMethods.ChangeonSomething, null, "\\fusion"],
  Deltasub: [ThermodynamicsMethods.ChangeonSomething, null, "\\sublimation"],
  Deltavap: [ThermodynamicsMethods.ChangeonSomething, null, "\\vaporization"],
  xrxn: [ThermodynamicsMethods.Macro, "\\xi"],
  Partial: ThermodynamicsMethods.Partial,
  PartialSecond: ThermodynamicsMethods.PartialSecond,
  PartialMixSecond: ThermodynamicsMethods.PartialMixSecond,
  Partialinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial #1/\\partial #2\\right)_{#3}', 3],
  PartialSecondinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial^2 #1/\\partial #2^2\\right)_{#3}', 3],
  PartialMixSecondinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial^2 #1/\\partial #2 \\partial #3\\right)_{#4}', 4],
  PartialBigg: [ThermodynamicsMethods.Partial, '\\Biggl', '\\Biggr'],
  PartialSecondBigg: [ThermodynamicsMethods.PartialSecond,
    '\\Biggl', '\\Biggr'],
  PartialMixSecondBigg: [ThermodynamicsMethods.PartialMixSecond,
    '\\Biggl', '\\Biggr'],
  Partialbigg: [ThermodynamicsMethods.Partial,
    '\\biggl', '\\biggr'],
  PartialSecondbigg: [ThermodynamicsMethods.PartialSecond,
    '\\biggl', '\\biggr'],
  PartialMixSecondbigg: [ThermodynamicsMethods.PartialMixSecond,
    '\\biggl', '\\biggr'],
  Partialinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial #1/\\partial #2)_{#3}', 3],
  PartialSecondinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial^2 #1/\\partial #2^2)_{#3}', 3],
  PartialMixSecondinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial^2 #1/\\partial #2 \\partial #3)_{#4}', 4],
  // FIXME: we could reprogram these to *check* instead of forcing the user?
  allbut: [ThermodynamicsMethods.Macro, '{#3}_{#1 \\neq #2}', 3, 'j'],
  allbutlastand: [ThermodynamicsMethods.Macro,
    '{#3}_{#1 \\neq #2,\\ncomponents}', 3, 'j'],
  allNs: [ThermodynamicsMethods.Macro, '\\vec{\\Nt}'],
  allNsbut: [ThermodynamicsMethods.Macro, '\\Nt_{#1\\neq #2}', 2, 'j'],
  allmus: [ThermodynamicsMethods.Macro, '\\vec{\\mu}'],
  allmusbut: [ThermodynamicsMethods.Macro, '\\mu_{#1\\neq #2}', 2, 'j'],
  allXs: [ThermodynamicsMethods.Macro, '\\vec{x}'],
  allXsbut: [ThermodynamicsMethods.Macro,
    'x_{#1\\neq #2,\\ncomponents}', 2, 'j'],
  allYs: [ThermodynamicsMethods.Macro, '\\vec{y}'],
  allYsbut: [ThermodynamicsMethods.Macro,
    'y_{#1\\neq #2,\\ncomponents}', 2, 'j'],
  allMs: [ThermodynamicsMethods.Macro, '\\vec{m}'],
  allMsbut: [ThermodynamicsMethods.Macro, 'm_{#1\\neq #2}', 2, 'j'],
  allWs: [ThermodynamicsMethods.Macro, '\\vec{w}'],
  allWsbut: [ThermodynamicsMethods.Macro,
    'w_{#1\\neq #2,\\ncomponents}', 2, 'j'],
  Jacobian: [ThermodynamicsMethods.Macro,
    '\\frac{\\partial(#1)}{\\partial(#2)}', 2],
  // Jacobiandet
  sumall: [ThermodynamicsMethods.Macro, "\\sum_{#2=1}^{\\ncomponents}", 2],
  sumallbutlast: [ThermodynamicsMethods.Macro,
    "\\sum_{#2=1}^{\\ncomponents-1}", 2],
  prodall: [ThermodynamicsMethods.Macro, "\\prod_{#2=1}^{\\ncomponents}", 2],
  IG: [ThermodynamicsMethods.Macro, '{\\text{IG}}'],
  IS: [ThermodynamicsMethods.Macro, '{\\text{IS}}'],
  IGM: [ThermodynamicsMethods.Macro, '{\\text{IGM}}'],
  Epot: [ThermodynamicsMethods.Macro, 'E'],
});

/**
 * Environments for the thermodynamics package
 */
new EnvironmentMap('Thermodynamics-environments', ParseMethods.environment, {
  thermointensiveplain: null,
//  thermoextensiveplain:
//  thermoextensivesuperscript:
//  thermointensivelowercase:
//  thermolongpm:
//  thermoshortpm:
//  thermoparentheses: [ThermodynamicsMethods.SetPartialDelimiters, "(", ')', ')'],
//  thermobrackets: [ThermodynamicsMethods.SetPartialDelimiters, "[", ']', ']'],
//  thermobraces:
//  thermobar:
//  thermoplain:
//  thermosubscripts:
//  thermoNOsubscripts:
//  thermomolesrange:
});
