/*************************************************************
 *
 *  Copyright (c) 2026 The MathJax Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * @file Mappings file for the thermodynamics package.
 *
 * @author kaiserkarl31@yahoo.com (Karl D. Hammond)
 */

import ParseMethods from '../ParseMethods.js';
import ThermodynamicsMethods from './ThermodynamicsMethods.js';
import { CommandMap,EnvironmentMap } from '../TokenMap.js';

/**
 * Macros for the thermodynamics package
 */
new CommandMap ('Thermodynamics-macros', {
  // Internal macros
  AreaSymbol: [ThermodynamicsMethods.Macro, 'a'],
  TotalEnergySymbol: [ThermodynamicsMethods.Macro, 'E'],
  EnthalpySymbol: [ThermodynamicsMethods.Macro, 'H'],
  EntropySymbol: [ThermodynamicsMethods.Macro, 'S'],
  GibbsSymbol: [ThermodynamicsMethods.Macro, 'G'],
  HelmholtzSymbol: [ThermodynamicsMethods.Macro, 'A'],
  InternalEnergySymbol: [ThermodynamicsMethods.Macro, 'U'],
  VolumeSymbol: [ThermodynamicsMethods.Macro, 'V'],
  heatcapacitysymbol: [ThermodynamicsMethods.Macro, 'C'],
  ncomponents: [ThermodynamicsMethods.Macro, 'C'],
  compressibilitysymbol: [ThermodynamicsMethods.Macro, '\\kappa'],
  expansivitysymbol: [ThermodynamicsMethods.Macro, '\\alpha'],
  extensive: ThermodynamicsMethods.ExtensiveProperty,
  intensive: ThermodynamicsMethods.IntensiveProperty,
  specific: ThermodynamicsMethods.SpecificProperty,
  // FIXME these are here to implement intensive-lowercase, but...
  //       there really needs to be a better way to do this!
  areasymbol: [ThermodynamicsMethods.Macro, 'a'],
  totalenergysymbol: [ThermodynamicsMethods.Macro, 'e'],
  enthalpysymbol: [ThermodynamicsMethods.Macro, 'h'],
  entropysymbol: [ThermodynamicsMethods.Macro, 's'],
  gibbssymbol: [ThermodynamicsMethods.Macro, 'g'],
  helmholtzsymbol: [ThermodynamicsMethods.Macro, 'a'],
  internalenergysymbol: [ThermodynamicsMethods.Macro, 'u'],
  volumesymbol: [ThermodynamicsMethods.Macro, 'v'],
  // user-facing symbols
  dbar: [ThermodynamicsMethods.Macro, '\u0111'],
  residual: [ThermodynamicsMethods.Macro, "{{R}}"],
  excess: [ThermodynamicsMethods.Macro, "{{E}}"],
  partialmolar: ThermodynamicsMethods.PartialMolarMacro,
  NewExtensiveProperty: ThermodynamicsMethods.NewExtensiveProperty,
  NewPartialMolarProperty: ThermodynamicsMethods.NewPartialMolarProperty,
  NewExcessProperty: ThermodynamicsMethods.NewExcessProperty,
  NewResidualProperty: ThermodynamicsMethods.NewResidualProperty,
  NewThermodynamicProperty: ThermodynamicsMethods.NewThermodynamicProperty,
  At: [ThermodynamicsMethods.Macro, '\\extensive{\\AreaSymbol}'],
  Am: [ThermodynamicsMethods.Macro, '\\intensive{\\AreaSymbol}'],
  As: [ThermodynamicsMethods.Macro, '\\specific{\\AreaSymbol}'],
  Apm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\AreaSymbol}'],
  Et: [ThermodynamicsMethods.Macro, '\\extensive{\\TotalEnergySymbol}'],
  Em: [ThermodynamicsMethods.Macro, '\\intensive{\\TotalEnergySymbol}'],
  Es: [ThermodynamicsMethods.Macro, '\\specific{\\TotalEnergySymbol}'],
  Epm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\TotalEnergySymbol}'],
  EEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\TotalEnergySymbol}','\\excess'],
  EE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\TotalEnergySymbol}','\\excess'],
  EEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\TotalEnergySymbol}','\\excess'],
  EEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\TotalEnergySymbol}','\\excess'],
  ERt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\TotalEnergySymbol}','\\residual'],
  ER: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\TotalEnergySymbol}','\\residual'],
  ERs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\TotalEnergySymbol}','\\residual'],
  ERpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\TotalEnergySymbol}','\\residual'],
  Ft: [ThermodynamicsMethods.Macro, '\\extensive{\\HelmholtzSymbol}'],
  Fm: [ThermodynamicsMethods.Macro, '\\intensive{\\HelmholtzSymbol}'],
  Fs: [ThermodynamicsMethods.Macro, '\\specific{\\HelmholtzSymbol}'],
  FRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\HelmholtzSymbol}','\\residual'],
  FR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\HelmholtzSymbol}','\\residual'],
  FRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\HelmholtzSymbol}','\\residual'],
  FEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\HelmholtzSymbol}','\\excess'],
  FE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\HelmholtzSymbol}','\\excess'],
  FEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\HelmholtzSymbol}','\\excess'],
  Fpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\HelmholtzSymbol}'],
  FRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\HelmholtzSymbol}','\\residual'],
  FEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\HelmholtzSymbol}','\\excess'],
  Gt: [ThermodynamicsMethods.Macro, '\\extensive{\\GibbsSymbol}'],
  Gm: [ThermodynamicsMethods.Macro, '\\intensive{\\GibbsSymbol}'],
  Gs: [ThermodynamicsMethods.Macro, '\\specific{\\GibbsSymbol}'],
  Gpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\GibbsSymbol}'],
  GRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\GibbsSymbol}','\\residual'],
  GR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\GibbsSymbol}','\\residual'],
  GRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\GibbsSymbol}','\\residual'],
  GEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\GibbsSymbol}','\\excess'],
  GE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\GibbsSymbol}','\\excess'],
  GEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\GibbsSymbol}','\\excess'],
  GRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\GibbsSymbol}','\\residual'],
  GEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\GibbsSymbol}','\\excess'],
  Ht: [ThermodynamicsMethods.Macro, '\\extensive{\\EnthalpySymbol}'],
  Hm: [ThermodynamicsMethods.Macro, '\\intensive{\\EnthalpySymbol}'],
  Hs: [ThermodynamicsMethods.Macro, '\\specific{\\EnthalpySymbol}'],
  Hpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\EnthalpySymbol}'],
  HRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\EnthalpySymbol}','\\residual'],
  HR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EnthalpySymbol}','\\residual'],
  HRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\EnthalpySymbol}','\\residual'],
  HEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\EnthalpySymbol}','\\excess'],
  HE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EnthalpySymbol}','\\excess'],
  HEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\EnthalpySymbol}','\\excess'],
  HRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EnthalpySymbol}','\\residual'],
  HEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EnthalpySymbol}','\\excess'],
  Lt: [ThermodynamicsMethods.Macro, '\\extensive{\\Omega}'],
  Lm: [ThermodynamicsMethods.Macro, '\\intensive{\\Omega}'],
  Ls: [ThermodynamicsMethods.Macro, '\\specific{\\Omega}'],
  Lpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\Omega}'],
  LEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\Omega}','\\excess'],
  LE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\Omega}','\\excess'],
  LEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\Omega}','\\excess'],
  LEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\Omega}','\\excess'],
  LRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\Omega}','\\residual'],
  LR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\Omega}','\\residual'],
  LRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\Omega}','\\residual'],
  LRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\Omega}','\\residual'],
  Nt: [ThermodynamicsMethods.Macro, 'n'],
  Qt: [ThermodynamicsMethods.Macro, '\\extensive{Q}'],
  Qm: [ThermodynamicsMethods.Macro, '\\intensive{Q}'],
  Qs: [ThermodynamicsMethods.Macro, '\\specific{Q}'],
  St: [ThermodynamicsMethods.Macro, '\\extensive{\\EntropySymbol}'],
  Sm: [ThermodynamicsMethods.Macro, '\\intensive{\\EntropySymbol}'],
  Ss: [ThermodynamicsMethods.Macro, '\\specific{\\EntropySymbol}'],
  Spm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\EntropySymbol}'],
  SRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\EntropySymbol}','\\residual'],
  SR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EntropySymbol}','\\residual'],
  SRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\EntropySymbol}','\\residual'],
  SRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EntropySymbol}','\\residual'],
  SEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\EntropySymbol}','\\excess'],
  SE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\EntropySymbol}','\\excess'],
  SEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\EntropySymbol}','\\excess'],
  SEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\intensive{\\EntropySymbol}','\\excess'],
  Ut: [ThermodynamicsMethods.Macro, '\\extensive{\\InternalEnergySymbol}'],
  Um: [ThermodynamicsMethods.Macro, '\\intensive{\\InternalEnergySymbol}'],
  Us: [ThermodynamicsMethods.Macro, '\\specific{\\InternalEnergySymbol}'],
  Upm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\InternalEnergySymbol}'],
  URt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\InternalEnergySymbol}','\\residual'],
  UR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\InternalEnergySymbol}','\\residual'],
  URs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\InternalEnergySymbol}','\\residual'],
  URpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\InternalEnergySymbol','\\residual'],
  UEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\InternalEnergySymbol}','\\excess'],
  UE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\InternalEnergySymbol}','\\excess'],
  UEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\InternalEnergySymbol}','\\excess'],
  UEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\InternalEnergySymbol','\\excess'],
  Vt: [ThermodynamicsMethods.Macro, '\\extensive{\\VolumeSymbol}'],
  Vm: [ThermodynamicsMethods.Macro, '\\intensive{\\VolumeSymbol}'],
  Vs: [ThermodynamicsMethods.Macro, '\\specific{\\VolumeSymbol}'],
  Vpm: [ThermodynamicsMethods.Macro, '\\partialmolar{\\VolumeSymbol}'],
  VRt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\VolumeSymbol}','\\residual'],
  VR: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\VolumeSymbol}','\\residual'],
  VRs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\VolumeSymbol}','\\residual'],
  VRpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\VolumeSymbol', '\\residual'],
  VEt: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\extensive{\\VolumeSymbol}','\\excess'],
  VE: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\intensive{\\VolumeSymbol}','\\excess'],
  VEs: [ThermodynamicsMethods.SuperscriptedSymbol,
    '\\specific{\\VolumeSymbol}','\\excess'],
  VEpm: [ThermodynamicsMethods.PartialMolarSuperscripted,
    '\\VolumeSymbol','\\excess'],
  Wt: [ThermodynamicsMethods.Macro, '\\extensive{W}'],
  Wm: [ThermodynamicsMethods.Macro, '\\intensive{W}'],
  Ws: [ThermodynamicsMethods.Macro, '\\specific{W}'],
  cP: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\intensive{\\heatcapacitysymbol}', 'P'],
  cPt: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\extensive{\\heatcapacitysymbol}', 'P'],
  cPs: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\specific{\\heatcapacitysymbol}', 'P'],
  cPpm: [ThermodynamicsMethods.PartialMolarSubscripted,
        '\\intensive{\\heatcapacitysymbol}', 'P'],
  cVpm: [ThermodynamicsMethods.PartialMolarSubscripted,
        '\\intensive{\\heatcapacitysymbol}', '\\VolumeSymbol'],
  cV: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\intensive{\\heatcapacitysymbol}', '\\VolumeSymbol'],
  cVt: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\extensive{\\heatcapacitysymbol}', '\\VolumeSymbol'],
  cVs: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\specific{\\heatcapacitysymbol}', '\\VolumeSymbol'],
  kappaT: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\compressibilitysymbol', 'T'],
  kappaS: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\compressibilitysymbol', 'S'],
  alphaP: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\expansivitysymbol', 'P'],
  alphaS: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\expansivitysymbol', '\\EntropySymbol'],
  muJT: [ThermodynamicsMethods.SubscriptedSymbol,
        '\\mu', '\\text{JT}'],
  fpure: [ThermodynamicsMethods.Macro, 'f'],
  fmix: [ThermodynamicsMethods.Macro, '\\hat f'],
  phipure: [ThermodynamicsMethods.Macro, '\\phi'],
  phimix: [ThermodynamicsMethods.Macro, '\\hat\\phi'],
  actabs: [ThermodynamicsMethods.Macro, '\\lambda'],
  actrel: [ThermodynamicsMethods.Macro, 'a'],
  muit: [ThermodynamicsMethods.Macro, '\\mu'],
  gammait: [ThermodynamicsMethods.Macro, '\\gamma'],
  gammarat: [ThermodynamicsMethods.Macro, '\\gamma^*'],
  gammamol: [ThermodynamicsMethods.Macro, '\\gamma^\\Box'],
  Henryrat: [ThermodynamicsMethods.Macro, 'h'],
  Henrymol: [ThermodynamicsMethods.Macro, '\\mathcal{H}'],
  sat: [ThermodynamicsMethods.Macro, '\\text{sat}'],
  fsat: [ThermodynamicsMethods.Macro, 'f^{\\sat}'],
  Psat: [ThermodynamicsMethods.Macro, 'P^{\\sat}'],
  Pvap: [ThermodynamicsMethods.Macro, 'P^{\\sat}'],
  phisat: [ThermodynamicsMethods.Macro, '\\phi^{\\sat}'],
  std: [ThermodynamicsMethods.Macro, '\\circ'],
  Cstd: [ThermodynamicsMethods.Macro, 'C^{\\std}'],
  fstd: [ThermodynamicsMethods.Macro, 'f^{\\std}'],
  Pstd: [ThermodynamicsMethods.Macro, 'P^{\\std}'],
  mustd: [ThermodynamicsMethods.Macro, '\\mu^{\\std}'],
  mixing: [ThermodynamicsMethods.Macro, '\\text{mix}'],
  formation: [ThermodynamicsMethods.Macro, 'f'],
  fusion: [ThermodynamicsMethods.Macro, '\\text{fusion}'],
  reaction: [ThermodynamicsMethods.Macro, '\\text{rxn}'],
  sublimation: [ThermodynamicsMethods.Macro, '\\text{sub}'],
  vaporization: [ThermodynamicsMethods.Macro, '\\text{vap}'],
  Deltaf: [ThermodynamicsMethods.ChangeonSomething, "\\formation"],
  Deltamix: [ThermodynamicsMethods.ChangeonSomething, "\\mixing"],
  Deltarxn: [ThermodynamicsMethods.ChangeonSomething, "\\reaction"],
  Deltafus: [ThermodynamicsMethods.ChangeonSomething, null, "\\fusion"],
  Deltasub: [ThermodynamicsMethods.ChangeonSomething, null, "\\sublimation"],
  Deltavap: [ThermodynamicsMethods.ChangeonSomething, null, "\\vaporization"],
  xrxn: [ThermodynamicsMethods.Macro, "\\xi"],
  Partial: ThermodynamicsMethods.Partial,
  PartialSecond: ThermodynamicsMethods.PartialSecond,
  PartialMixSecond: ThermodynamicsMethods.PartialMixSecond,
  Partialinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial #1/\\partial #2\\right)_{#3}', 3],
  PartialSecondinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial^2 #1/\\partial #2^2\\right)_{#3}', 3],
  PartialMixSecondinline: [ThermodynamicsMethods.Macro,
    '\\left(\\partial^2 #1/\\partial #2 \\partial #3\\right)_{#4}', 4],
  PartialBigg: [ThermodynamicsMethods.Partial, '\\Biggl', '\\Biggr'],
  PartialSecondBigg: [ThermodynamicsMethods.PartialSecond,
    '\\Biggl', '\\Biggr'],
  PartialMixSecondBigg: [ThermodynamicsMethods.PartialMixSecond,
    '\\Biggl', '\\Biggr'],
  Partialbigg: [ThermodynamicsMethods.Partial,
    '\\biggl', '\\biggr'],
  PartialSecondbigg: [ThermodynamicsMethods.PartialSecond,
    '\\biggl', '\\biggr'],
  PartialMixSecondbigg: [ThermodynamicsMethods.PartialMixSecond,
    '\\biggl', '\\biggr'],
  Partialinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial #1/\\partial #2)_{#3}', 3],
  PartialSecondinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial^2 #1/\\partial #2^2)_{#3}', 3],
  PartialMixSecondinlinetext: [ThermodynamicsMethods.Macro,
    '(\\partial^2 #1/\\partial #2 \\partial #3)_{#4}', 4],
  allbut: [ThermodynamicsMethods.AllThingsExcept, null],
  allbutlastand: [ThermodynamicsMethods.AllThingsExceptLastAnd, null],
  allNs: [ThermodynamicsMethods.AllThings, '\\Nt'],
  allNsbut: [ThermodynamicsMethods.AllThingsExcept, '\\Nt'],
  allmus: [ThermodynamicsMethods.AllThings, '\\mu'],
  allmusbut: [ThermodynamicsMethods.AllThingsExcept, '\\mu'],
  allXs: [ThermodynamicsMethods.AllThings, 'x'],
  allXsbut: [ThermodynamicsMethods.AllThingsExceptLastAnd, 'x'],
  allYs: [ThermodynamicsMethods.AllThings, 'y'],
  allYsbut: [ThermodynamicsMethods.AllThingsExceptLastAnd, 'y'],
  allMs: [ThermodynamicsMethods.AllThings, 'm'],
  allMsbut: [ThermodynamicsMethods.AllThingsExcept, 'm'],
  allWs: [ThermodynamicsMethods.AllThings, 'w'],
  allWsbut: [ThermodynamicsMethods.AllThingsExcept, 'w'],
  Jacobian: [ThermodynamicsMethods.Macro,
    '\\frac{\\partial(#1)}{\\partial(#2)}', 2],
  Jacobiandet: ThermodynamicsMethods.JacobianDeterminant,
  sumall: [ThermodynamicsMethods.Macro, "\\sum_{#2=1}^{\\ncomponents}", 2],
  sumallbutlast: [ThermodynamicsMethods.Macro,
    "\\sum_{#2=1}^{\\ncomponents-1}", 2],
  prodall: [ThermodynamicsMethods.Macro, "\\prod_{#2=1}^{\\ncomponents}", 2],
  IG: [ThermodynamicsMethods.Macro, '{\\text{IG}}'],
  IS: [ThermodynamicsMethods.Macro, '{\\text{IS}}'],
  IGM: [ThermodynamicsMethods.Macro, '{\\text{IGM}}'],
  Epot: [ThermodynamicsMethods.Macro, 'E'],
});

/**
 * Environments for the thermodynamics package
 */
new EnvironmentMap('Thermodynamics-environments', ParseMethods.environment, {
  thermointensiveplain: [ThermodynamicsMethods.LocallyChangeEISappearance,
    null, 'intensive-plain'],
  thermoextensiveplain: [ThermodynamicsMethods.LocallyChangeEISappearance,
    null, 'extensive-plain'],
  thermoextensivesuperscript: [ThermodynamicsMethods.LocallyChangeEISappearance,
      null, 'extensive-superscript'],
  thermointensivelowercase: [ThermodynamicsMethods.LocallyChangeEISappearance,
      null, 'intensive-lowercase'],
  thermoparentheses: [ThermodynamicsMethods.LocallyChangeDelimiters, null, "(", ')', ')'],
  thermobrackets: [ThermodynamicsMethods.LocallyChangeDelimiters, null, '[', ']', ']'],
  thermobraces: [ThermodynamicsMethods.LocallyChangeDelimiters, null, '\\{', '\\}', '\\}'],
  thermobar: [ThermodynamicsMethods.LocallyChangeDelimiters, null, '.', '\\rvert', '.'],
  thermoplain: [ThermodynamicsMethods.LocallyChangeDelimiters, null, '.', '.', '.'],
  thermolongpm: [ThermodynamicsMethods.LocalLongPm, null],
  thermoshortpm: [ThermodynamicsMethods.LocalShortPm, null],
  thermosubscripts: [ThermodynamicsMethods.LocalSubscripts, null],
  thermoNOsubscripts: [ThermodynamicsMethods.LocalNoSubscripts, null],
  thermomolesindex: [ThermodynamicsMethods.LocalMolesIndex, null],
  thermomolesrange: [ThermodynamicsMethods.LocalMolesRange, null],
});
