* MOVABLELIMITS:false also in attributes
   Only mo s need it. Sort out explicitly in mi to mo.
   None mo need it in properties.


   
* Running test Enclosed left right	[31mFAIL[37m
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center","columnspacing":"1em","rowspacing":"4pt","columnlines":""},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true,"padding":0},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center","columnspacing":"1em","rowspacing":"4pt","columnlines":"solid none"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}

** The columnlines: solid none seems wrong

** padding="0" should not be there?

*** Add a test for three columns for colums solid node

*** clean isFrame (could be a private data attribute)

* Running test Array framed dashed row	[31mFAIL[37m
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true,"padding":0},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnspacing":"1em","rowspacing":"4pt","columnlines":"","rowlines":"dashed"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"rowspacing":"4pt","columnspacing":"1em","rowlines":"dashed","columnlines":""},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}

** columnalign: center is not necessary?

** padding="0" should be there?

   
* Running test Array framed solid row	[31mFAIL[37m
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true,"padding":0},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnspacing":"1em","rowspacing":"4pt","columnlines":"","rowlines":"solid"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"rowspacing":"4pt","columnspacing":"1em","rowlines":"solid","columnlines":""},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}

** columnalign: center is not necessary?

** isFrame missing 

** padding="0" missing

   
* Running test Array framed dashed column	[31mFAIL[37m
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true,"padding":0},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center center","columnspacing":"1em","rowspacing":"4pt","columnlines":"dashed"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center center","rowspacing":"4pt","columnspacing":"1em","columnlines":"dashed"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}

** isFrame missing 

** padding="0" missing

   
* Running test Array framed solid column	[31mFAIL[37m
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right","isFrame":true,"padding":0},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center center","columnspacing":"1em","rowspacing":"4pt","columnlines":"solid"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"menclose","texClass":0,"attributes":{"notation":"left right"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtable","texClass":0,"attributes":{"columnalign":"center center","rowspacing":"4pt","columnspacing":"1em","columnlines":"solid"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"useHeight":1},"childNodes":[{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]}],"isInferred":true}]}]},{"kind":"mtr","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isInferred":true}]},{"kind":"mtd","texClass":null,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}]}]}],"isInferred":true}]}],"isInferred":true}]}


** isFrame missing 

** padding="0" missing

   
* Running test Negation Complex	[FIXED]
  Actual: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]},{"kind":"mo","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{},"childNodes":[{"kind":"text","text":"≠"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]},{"kind":"mo","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix","accent":true},"properties":{},"childNodes":[{"kind":"text","text":"↛"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]},{"kind":"mo","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{},"childNodes":[{"kind":"text","text":"≰"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}
  Expected: 
  {"kind":"math","texClass":0,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"a"}]},{"kind":"mo","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{},"childNodes":[{"kind":"text","text":"≠"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]},{"kind":"mo","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{},"childNodes":[{"kind":"text","text":"↛"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]},{"kind":"mo","texClass":2,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{},"childNodes":[{"kind":"text","text":"≰"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"d"}]}],"isInferred":true}]}


** texclass of neither-less-than-nor-equal should be 3 not 2

   3 is correct.

** Why is there an inherited accent=true for the \not\rightarrow?

* Positive Spacing

** scriptlevel:0 in properties in the old version but not the new one.

** mathsize:normal in attributes. Should that be there? It is being pushed.

* Negative Spacing

** same as Positive spacing.

* Limits SubSup	[FIXED]

** Check whether taking the coreMO texclass is valid.

   
* Modulo

** mathchoice: How are we going to handle this in the future?
   mml mathchoice node

** mathsize problem.

* Mathop

* Running test Mathop Super	[31mFAIL[37m  [FIXED]
Actual: 
{"kind":"math","texClass":3,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mover","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mo","texClass":3,"attributes":{"mathvariant":"normal","movablelimits":true,"lspace":"0","rspace":"0"},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{"movablelimits":true,"movesupsub":true,"texprimestyle":true},"childNodes":[{"kind":"text","text":"a"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isEmbellished":true}],"isInferred":true,"isEmbellished":true}],"isEmbellished":true}
Expected: 
{"kind":"math","texClass":3,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mover","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"movesupsub":true},"childNodes":[{"kind":"mo","texClass":3,"attributes":{"lspace":"0","rspace":"0","movablelimits":true},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{"movablelimits":true,"texprimestyle":true},"childNodes":[{"kind":"text","text":"a"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"b"}]}],"isEmbellished":true}],"isInferred":true,"isEmbellished":true}],"isEmbellished":true}

** movesupsub is in the mo rather than the mover
   It is in the data structure for both. Why is it not output?

   Removed movesupsub explicitly in mi2mo.

   
* Running test Mathop Sub	[31mFAIL[37m [FIXED]
Actual: 
{"kind":"math","texClass":3,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"munder","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mo","texClass":3,"attributes":{"mathvariant":"normal","movablelimits":true,"lspace":"0","rspace":"0"},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{"movablelimits":true,"movesupsub":true},"childNodes":[{"kind":"text","text":"a"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{"texprimestyle":true},"childNodes":[{"kind":"text","text":"b"}]}],"isEmbellished":true}],"isInferred":true,"isEmbellished":true}],"isEmbellished":true}
Expected: 
{"kind":"math","texClass":3,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"munder","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"movesupsub":true},"childNodes":[{"kind":"mo","texClass":3,"attributes":{"lspace":"0","rspace":"0","movablelimits":true},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{"movablelimits":true},"childNodes":[{"kind":"text","text":"a"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{"texprimestyle":true},"childNodes":[{"kind":"text","text":"b"}]}],"isEmbellished":true}],"isInferred":true,"isEmbellished":true}],"isEmbellished":true}

** see Mathop Super


** Added and working:

parserTest.runTest(
  'Mathop Sub Super', '\\mathop{\\rm a}_b^c',
  {"kind":"math","texClass":3,"attributes":{"display":"block"},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"mrow","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{},"childNodes":[{"kind":"munderover","texClass":3,"attributes":{},"inherited":{"displaystyle":true,"scriptlevel":0},"properties":{"movesupsub":true},"childNodes":[{"kind":"mo","texClass":3,"attributes":{"lspace":"0","rspace":"0","movablelimits":true},"inherited":{"displaystyle":true,"scriptlevel":0,"form":"infix"},"properties":{"movablelimits":true,"texprimestyle":true},"childNodes":[{"kind":"text","text":"a"}],"isEmbellished":true},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{"texprimestyle":true},"childNodes":[{"kind":"text","text":"b"}]},{"kind":"mi","texClass":0,"attributes":{},"inherited":{"displaystyle":false,"scriptlevel":1,"mathvariant":"italic"},"properties":{},"childNodes":[{"kind":"text","text":"c"}]}],"isEmbellished":true}],"isInferred":true,"isEmbellished":true}],"isEmbellished":true}
);

* Arrays: Which elements have to inherit the alignment attributes? 
** mtr from mtable etc.
** In the old data structure the inherit elements were there
** In the new data structure mtr has INHERIT set but it does not show up in the JSON.


*** That is old, I believe.

* With delims:
  
** texWithDelims vs withDelims: This seems to have changed.

* Output weakness: Stretchies with Choose etc. in subscripts do not look good.

* Mathsize normal problem in various base tests (in mspace elements)
** Mathsize does not occur in the original JSON output, but now it does.
** It's not incorrect in the mspace elements, but should it be there?

*** scriptlevels should not be there (it is not). No need for mathsize:normal!

* infix/prefix/postfix: Vertical bar problem. 
** Mine seem to be correct, but they don't correspond to MJ2 where they all appear infix.
** Consequently I am missing texatom wrappers.

*** Solved by going with post/prefix over infix.

*** Why does prefix texclass propagate but postfix texclass does not?

* Movablelimits hack! [DONE]

** Only in case it is an mo, look it up in the operator table.

*** Solved!

* useHeight vs displaystyle=false in Subarray and smallMatrix

** Turns off strutting, is it still important?
** Can probably go!

** We currently get the old style:
   useHeight=false, displaystyle=false is inherited, hence omitted from the attributes
   The master version seems to be wrong.

# NEW
* Does not work: dddot, ddddot
* menclose does not work yet, correct?
* What does SkipLimits do?  I assume that is internal.
* How do we want to organise the configurations?
* Can I generate a bevelled fraction with Tex? \Big/?
