name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Compile and test MathJax
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install packages
        run: |
          pnpm -r i
          pnpm --silent link:src

      - name: Compile MathJax
        run: |
          pnpm --silent mjs:compile
          pnpm --silent copy:assets mjs
          components/bin/makeAll --mjs --terse --build --copy components/mjs
          pnpm --silent cjs:compile
          pnpm --silent cjs:components:src:build
          pnpm --silent copy:assets cjs
          components/bin/makeAll --cjs --terse --build --copy components/cjs
          pnpm --silent copy:pkg cjs

      - name: Build tests
        run: pnpm tsc -p testsuite/tsconfig.json
          
      - name: Run tests
        run: pnpm --silent test:gh

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mathjax/MathJax-src
